// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: bank/tx.proto

package pb

import (
	pb "github.com/joseluis8906/project-layout/pkg/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Number string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *TxAccount) Reset() {
	*x = TxAccount{}
	mi := &file_bank_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxAccount) ProtoMessage() {}

func (x *TxAccount) ProtoReflect() protoreflect.Message {
	mi := &file_bank_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxAccount.ProtoReflect.Descriptor instead.
func (*TxAccount) Descriptor() ([]byte, []int) {
	return file_bank_tx_proto_rawDescGZIP(), []int{0}
}

func (x *TxAccount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TxAccount) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type WithdrawRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *TxAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Amount  *pb.Money  `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	mi := &file_bank_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_bank_tx_proto_rawDescGZIP(), []int{1}
}

func (x *WithdrawRequest) GetAccount() *TxAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *WithdrawRequest) GetAmount() *pb.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

type WithdrawResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *WithdrawResponse) Reset() {
	*x = WithdrawResponse{}
	mi := &file_bank_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResponse) ProtoMessage() {}

func (x *WithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResponse.ProtoReflect.Descriptor instead.
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return file_bank_tx_proto_rawDescGZIP(), []int{2}
}

func (x *WithdrawResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DirectDepositRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *TxAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Amount  *pb.Money  `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *DirectDepositRequest) Reset() {
	*x = DirectDepositRequest{}
	mi := &file_bank_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectDepositRequest) ProtoMessage() {}

func (x *DirectDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectDepositRequest.ProtoReflect.Descriptor instead.
func (*DirectDepositRequest) Descriptor() ([]byte, []int) {
	return file_bank_tx_proto_rawDescGZIP(), []int{3}
}

func (x *DirectDepositRequest) GetAccount() *TxAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *DirectDepositRequest) GetAmount() *pb.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

type DirectDepositResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DirectDepositResponse) Reset() {
	*x = DirectDepositResponse{}
	mi := &file_bank_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectDepositResponse) ProtoMessage() {}

func (x *DirectDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectDepositResponse.ProtoReflect.Descriptor instead.
func (*DirectDepositResponse) Descriptor() ([]byte, []int) {
	return file_bank_tx_proto_rawDescGZIP(), []int{4}
}

func (x *DirectDepositResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_bank_tx_proto protoreflect.FileDescriptor

var file_bank_tx_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x62, 0x61, 0x6e, 0x6b, 0x1a, 0x0d, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x09, 0x54, 0x78, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x64, 0x0a,
	0x0f, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x29, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x54, 0x78, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x2a, 0x0a, 0x10, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x69, 0x0a, 0x14, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x2e,
	0x54, 0x78, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2e, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2f, 0x0a, 0x15, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x90, 0x01, 0x0a, 0x09,
	0x54, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x12, 0x15, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x62,
	0x61, 0x6e, 0x6b, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x1a, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39,
	0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x73,
	0x65, 0x6c, 0x75, 0x69, 0x73, 0x38, 0x39, 0x30, 0x36, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x2d, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_bank_tx_proto_rawDescOnce sync.Once
	file_bank_tx_proto_rawDescData = file_bank_tx_proto_rawDesc
)

func file_bank_tx_proto_rawDescGZIP() []byte {
	file_bank_tx_proto_rawDescOnce.Do(func() {
		file_bank_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_bank_tx_proto_rawDescData)
	})
	return file_bank_tx_proto_rawDescData
}

var file_bank_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bank_tx_proto_goTypes = []any{
	(*TxAccount)(nil),             // 0: bank.TxAccount
	(*WithdrawRequest)(nil),       // 1: bank.WithdrawRequest
	(*WithdrawResponse)(nil),      // 2: bank.WithdrawResponse
	(*DirectDepositRequest)(nil),  // 3: bank.DirectDepositRequest
	(*DirectDepositResponse)(nil), // 4: bank.DirectDepositResponse
	(*pb.Money)(nil),              // 5: company.Money
}
var file_bank_tx_proto_depIdxs = []int32{
	0, // 0: bank.WithdrawRequest.account:type_name -> bank.TxAccount
	5, // 1: bank.WithdrawRequest.amount:type_name -> company.Money
	0, // 2: bank.DirectDepositRequest.account:type_name -> bank.TxAccount
	5, // 3: bank.DirectDepositRequest.amount:type_name -> company.Money
	1, // 4: bank.TxService.Withdraw:input_type -> bank.WithdrawRequest
	3, // 5: bank.TxService.DirectDeposit:input_type -> bank.DirectDepositRequest
	2, // 6: bank.TxService.Withdraw:output_type -> bank.WithdrawResponse
	4, // 7: bank.TxService.DirectDeposit:output_type -> bank.DirectDepositResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bank_tx_proto_init() }
func file_bank_tx_proto_init() {
	if File_bank_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bank_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bank_tx_proto_goTypes,
		DependencyIndexes: file_bank_tx_proto_depIdxs,
		MessageInfos:      file_bank_tx_proto_msgTypes,
	}.Build()
	File_bank_tx_proto = out.File
	file_bank_tx_proto_rawDesc = nil
	file_bank_tx_proto_goTypes = nil
	file_bank_tx_proto_depIdxs = nil
}
