// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: banking/tx.proto

package pb

import (
	pb "github.com/joseluis8906/project-layout/pkg/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcBank *TxBank   `protobuf:"bytes,1,opt,name=src_bank,json=srcBank,proto3" json:"src_bank,omitempty"`
	DstBank *TxBank   `protobuf:"bytes,2,opt,name=dst_bank,json=dstBank,proto3" json:"dst_bank,omitempty"`
	Amount  *pb.Money `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *InitTxRequest) Reset() {
	*x = InitTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banking_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTxRequest) ProtoMessage() {}

func (x *InitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banking_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitTxRequest.ProtoReflect.Descriptor instead.
func (*InitTxRequest) Descriptor() ([]byte, []int) {
	return file_banking_tx_proto_rawDescGZIP(), []int{0}
}

func (x *InitTxRequest) GetSrcBank() *TxBank {
	if x != nil {
		return x.SrcBank
	}
	return nil
}

func (x *InitTxRequest) GetDstBank() *TxBank {
	if x != nil {
		return x.DstBank
	}
	return nil
}

func (x *InitTxRequest) GetAmount() *pb.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

type InitTxJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SrcBank *TxBank   `protobuf:"bytes,2,opt,name=src_bank,json=srcBank,proto3" json:"src_bank,omitempty"`
	DstBank *TxBank   `protobuf:"bytes,3,opt,name=dst_bank,json=dstBank,proto3" json:"dst_bank,omitempty"`
	Amount  *pb.Money `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *InitTxJob) Reset() {
	*x = InitTxJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banking_tx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitTxJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTxJob) ProtoMessage() {}

func (x *InitTxJob) ProtoReflect() protoreflect.Message {
	mi := &file_banking_tx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitTxJob.ProtoReflect.Descriptor instead.
func (*InitTxJob) Descriptor() ([]byte, []int) {
	return file_banking_tx_proto_rawDescGZIP(), []int{1}
}

func (x *InitTxJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InitTxJob) GetSrcBank() *TxBank {
	if x != nil {
		return x.SrcBank
	}
	return nil
}

func (x *InitTxJob) GetDstBank() *TxBank {
	if x != nil {
		return x.DstBank
	}
	return nil
}

func (x *InitTxJob) GetAmount() *pb.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

type InitTxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
}

func (x *InitTxResponse) Reset() {
	*x = InitTxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banking_tx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTxResponse) ProtoMessage() {}

func (x *InitTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banking_tx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitTxResponse.ProtoReflect.Descriptor instead.
func (*InitTxResponse) Descriptor() ([]byte, []int) {
	return file_banking_tx_proto_rawDescGZIP(), []int{2}
}

func (x *InitTxResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type TxBank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Account *TxBank_Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *TxBank) Reset() {
	*x = TxBank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banking_tx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxBank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBank) ProtoMessage() {}

func (x *TxBank) ProtoReflect() protoreflect.Message {
	mi := &file_banking_tx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBank.ProtoReflect.Descriptor instead.
func (*TxBank) Descriptor() ([]byte, []int) {
	return file_banking_tx_proto_rawDescGZIP(), []int{3}
}

func (x *TxBank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TxBank) GetAccount() *TxBank_Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type CheckTxStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
}

func (x *CheckTxStatusRequest) Reset() {
	*x = CheckTxStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banking_tx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTxStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTxStatusRequest) ProtoMessage() {}

func (x *CheckTxStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banking_tx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTxStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckTxStatusRequest) Descriptor() ([]byte, []int) {
	return file_banking_tx_proto_rawDescGZIP(), []int{4}
}

func (x *CheckTxStatusRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type CheckTxStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckTxStatusResponse) Reset() {
	*x = CheckTxStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banking_tx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTxStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTxStatusResponse) ProtoMessage() {}

func (x *CheckTxStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banking_tx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTxStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckTxStatusResponse) Descriptor() ([]byte, []int) {
	return file_banking_tx_proto_rawDescGZIP(), []int{5}
}

func (x *CheckTxStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TxBank_Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Number string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *TxBank_Account) Reset() {
	*x = TxBank_Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banking_tx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxBank_Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBank_Account) ProtoMessage() {}

func (x *TxBank_Account) ProtoReflect() protoreflect.Message {
	mi := &file_banking_tx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBank_Account.ProtoReflect.Descriptor instead.
func (*TxBank_Account) Descriptor() ([]byte, []int) {
	return file_banking_tx_proto_rawDescGZIP(), []int{3, 0}
}

func (x *TxBank_Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TxBank_Account) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

var File_banking_tx_proto protoreflect.FileDescriptor

var file_banking_tx_proto_rawDesc = []byte{
	0x0a, 0x10, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x1a, 0x0d, 0x66, 0x69, 0x6e,
	0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x0d, 0x49,
	0x6e, 0x69, 0x74, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x08,
	0x73, 0x72, 0x63, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x78, 0x42, 0x61, 0x6e, 0x6b, 0x52,
	0x07, 0x73, 0x72, 0x63, 0x42, 0x61, 0x6e, 0x6b, 0x12, 0x2a, 0x0a, 0x08, 0x64, 0x73, 0x74, 0x5f,
	0x62, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x78, 0x42, 0x61, 0x6e, 0x6b, 0x52, 0x07, 0x64, 0x73, 0x74,
	0x42, 0x61, 0x6e, 0x6b, 0x12, 0x26, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2e, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x9b, 0x01, 0x0a,
	0x09, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x78, 0x4a, 0x6f, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x08, 0x73, 0x72,
	0x63, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x78, 0x42, 0x61, 0x6e, 0x6b, 0x52, 0x07, 0x73,
	0x72, 0x63, 0x42, 0x61, 0x6e, 0x6b, 0x12, 0x2a, 0x0a, 0x08, 0x64, 0x73, 0x74, 0x5f, 0x62, 0x61,
	0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x54, 0x78, 0x42, 0x61, 0x6e, 0x6b, 0x52, 0x07, 0x64, 0x73, 0x74, 0x42, 0x61,
	0x6e, 0x6b, 0x12, 0x26, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2e, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x25, 0x0a, 0x0e, 0x49, 0x6e,
	0x69, 0x74, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05,
	0x74, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49,
	0x64, 0x22, 0x86, 0x01, 0x0a, 0x06, 0x54, 0x78, 0x42, 0x61, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x31, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x78, 0x42, 0x61,
	0x6e, 0x6b, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x1a, 0x35, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x14, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x96, 0x01, 0x0a, 0x09, 0x54, 0x78, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x78,
	0x12, 0x16, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x54,
	0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1d, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6a, 0x6f, 0x73, 0x65, 0x6c, 0x75, 0x69, 0x73, 0x38, 0x39, 0x30, 0x36, 0x2f, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x2d, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_banking_tx_proto_rawDescOnce sync.Once
	file_banking_tx_proto_rawDescData = file_banking_tx_proto_rawDesc
)

func file_banking_tx_proto_rawDescGZIP() []byte {
	file_banking_tx_proto_rawDescOnce.Do(func() {
		file_banking_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_banking_tx_proto_rawDescData)
	})
	return file_banking_tx_proto_rawDescData
}

var file_banking_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_banking_tx_proto_goTypes = []interface{}{
	(*InitTxRequest)(nil),         // 0: banking.InitTxRequest
	(*InitTxJob)(nil),             // 1: banking.InitTxJob
	(*InitTxResponse)(nil),        // 2: banking.InitTxResponse
	(*TxBank)(nil),                // 3: banking.TxBank
	(*CheckTxStatusRequest)(nil),  // 4: banking.CheckTxStatusRequest
	(*CheckTxStatusResponse)(nil), // 5: banking.CheckTxStatusResponse
	(*TxBank_Account)(nil),        // 6: banking.TxBank.Account
	(*pb.Money)(nil),              // 7: company.Money
}
var file_banking_tx_proto_depIdxs = []int32{
	3, // 0: banking.InitTxRequest.src_bank:type_name -> banking.TxBank
	3, // 1: banking.InitTxRequest.dst_bank:type_name -> banking.TxBank
	7, // 2: banking.InitTxRequest.amount:type_name -> company.Money
	3, // 3: banking.InitTxJob.src_bank:type_name -> banking.TxBank
	3, // 4: banking.InitTxJob.dst_bank:type_name -> banking.TxBank
	7, // 5: banking.InitTxJob.amount:type_name -> company.Money
	6, // 6: banking.TxBank.account:type_name -> banking.TxBank.Account
	0, // 7: banking.TxService.InitTx:input_type -> banking.InitTxRequest
	4, // 8: banking.TxService.CheckTxStatus:input_type -> banking.CheckTxStatusRequest
	2, // 9: banking.TxService.InitTx:output_type -> banking.InitTxResponse
	5, // 10: banking.TxService.CheckTxStatus:output_type -> banking.CheckTxStatusResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_banking_tx_proto_init() }
func file_banking_tx_proto_init() {
	if File_banking_tx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_banking_tx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitTxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banking_tx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitTxJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banking_tx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitTxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banking_tx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxBank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banking_tx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTxStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banking_tx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTxStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banking_tx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxBank_Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_banking_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_banking_tx_proto_goTypes,
		DependencyIndexes: file_banking_tx_proto_depIdxs,
		MessageInfos:      file_banking_tx_proto_msgTypes,
	}.Build()
	File_banking_tx_proto = out.File
	file_banking_tx_proto_rawDesc = nil
	file_banking_tx_proto_goTypes = nil
	file_banking_tx_proto_depIdxs = nil
}
