// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: osp/osp.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OspService_Tx_FullMethodName = "/osp.OspService/Tx"
)

// OspServiceClient is the client API for OspService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OspServiceClient interface {
	Tx(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*TxResponse, error)
}

type ospServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOspServiceClient(cc grpc.ClientConnInterface) OspServiceClient {
	return &ospServiceClient{cc}
}

func (c *ospServiceClient) Tx(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*TxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxResponse)
	err := c.cc.Invoke(ctx, OspService_Tx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OspServiceServer is the server API for OspService service.
// All implementations must embed UnimplementedOspServiceServer
// for forward compatibility.
type OspServiceServer interface {
	Tx(context.Context, *TxRequest) (*TxResponse, error)
	mustEmbedUnimplementedOspServiceServer()
}

// UnimplementedOspServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOspServiceServer struct{}

func (UnimplementedOspServiceServer) Tx(context.Context, *TxRequest) (*TxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tx not implemented")
}
func (UnimplementedOspServiceServer) mustEmbedUnimplementedOspServiceServer() {}
func (UnimplementedOspServiceServer) testEmbeddedByValue()                    {}

// UnsafeOspServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OspServiceServer will
// result in compilation errors.
type UnsafeOspServiceServer interface {
	mustEmbedUnimplementedOspServiceServer()
}

func RegisterOspServiceServer(s grpc.ServiceRegistrar, srv OspServiceServer) {
	// If the following call pancis, it indicates UnimplementedOspServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OspService_ServiceDesc, srv)
}

func _OspService_Tx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OspServiceServer).Tx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OspService_Tx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OspServiceServer).Tx(ctx, req.(*TxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OspService_ServiceDesc is the grpc.ServiceDesc for OspService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OspService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osp.OspService",
	HandlerType: (*OspServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tx",
			Handler:    _OspService_Tx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osp/osp.proto",
}
