app:
  name: banking
otel:
  endpoint: http://yummies.local:4317
fluentd:
  host: yummies.local
  port: 24224
  network: tcp
  json: true
  tag: my.logs 
grpc:
  port: 50051
http:
  addr: ':9090'
nats:
  url: 'nats://yummies.local:4222'
kafka:
  bootstrap:
    servers: 'yummies.local:9092'
  acks: all
  group:
    id: banking
  auto:
    offset:
      reset: earliest
  topics:
    - v1.tested
mongodb:
  uri: 'mongodb://yummies:yummies@yummies.local:27017/banking?authMechanism=PLAIN'
pprof: true
