.PHONY: pb
pb: 
	@./scripts/generatepb.sh

# banking
.PHONY: banking-build
banking-build:
	@cd scripts/banking && make build

.PHONY: banking-run
banking-run:
	@cd scripts/banking && make run

.PHONY: banking-debug
banking-debug:
	@cd scripts/banking && make debug 

# mtx
.PHONY: mtx-build
mtx-build:
	@cd scripts/mtx && make build

.PHONY: mtx-run
mtx-run:
	@cd scripts/mtx && make run

.PHONY: mtx-debug
mtx-debug:
	@cd scripts/mtx && make debug

# osp
.PHONY: osp-build
osp-build:
	@cd scripts/osp && make build

.PHONY: osp-run
osp-run:
	@cd scripts/osp && make run

.PHONY: osp-debug
osp-debug:
	@cd scripts/osp && make debug

