.PHONY: pb
pb: 
	@./scripts/generatepb.sh
# mtx
.PHONY: mtx-build
mtx-build:
	@cd scripts/mtx && make build

.PHONY: mtx-run
mtx-run:
	@cd scripts/mtx && make run

.PHONY: mtx-debug
mtx-debug:
	@cd scripts/mtx && make debug

# osp
.PHONY: osp-build
osp-build:
	@cd scripts/osp && make build

.PHONY: osp-run
osp-run:
	@cd scripts/osp && make run

.PHONY: osp-debug
osp-debug:
	@cd scripts/osp && make debug

# bank
.PHONY: bank-build
bank-build:
	@cd scripts/bank && make build

.PHONY: bank-run
bank-run:
	@cd scripts/bank && make run

.PHONY: bank-debug
bank-debug:
	@cd scripts/bank && make debug

