.PHONY: pb
pb: 
	@./scripts/generatepb.sh

# banking
.PHONY: banking-build
banking-build:
	@cd scripts/banking && make build

.PHONY: banking-run
banking-run:
	@cd scripts/banking && make run

.PHONY: banking-debug
banking-debug:
	@cd scripts/banking && make debug 

