// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: events_v1.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type V1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *V1) Reset() {
	*x = V1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1) ProtoMessage() {}

func (x *V1) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1.ProtoReflect.Descriptor instead.
func (*V1) Descriptor() ([]byte, []int) {
	return file_events_v1_proto_rawDescGZIP(), []int{0}
}

type V1_Tested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OccurredOn int64  `protobuf:"varint,2,opt,name=occurred_on,json=occurredOn,proto3" json:"occurred_on,omitempty"`
	Msg        string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *V1_Tested) Reset() {
	*x = V1_Tested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1_Tested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1_Tested) ProtoMessage() {}

func (x *V1_Tested) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1_Tested.ProtoReflect.Descriptor instead.
func (*V1_Tested) Descriptor() ([]byte, []int) {
	return file_events_v1_proto_rawDescGZIP(), []int{0, 0}
}

func (x *V1_Tested) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *V1_Tested) GetOccurredOn() int64 {
	if x != nil {
		return x.OccurredOn
	}
	return 0
}

func (x *V1_Tested) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type V1_AccountCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OccurredOn int64                         `protobuf:"varint,2,opt,name=occurred_on,json=occurredOn,proto3" json:"occurred_on,omitempty"`
	Attributes *V1_AccountCreated_Attributes `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *V1_AccountCreated) Reset() {
	*x = V1_AccountCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1_AccountCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1_AccountCreated) ProtoMessage() {}

func (x *V1_AccountCreated) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1_AccountCreated.ProtoReflect.Descriptor instead.
func (*V1_AccountCreated) Descriptor() ([]byte, []int) {
	return file_events_v1_proto_rawDescGZIP(), []int{0, 1}
}

func (x *V1_AccountCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *V1_AccountCreated) GetOccurredOn() int64 {
	if x != nil {
		return x.OccurredOn
	}
	return 0
}

func (x *V1_AccountCreated) GetAttributes() *V1_AccountCreated_Attributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type V1_AccountCreated_Attributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Number string `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *V1_AccountCreated_Attributes) Reset() {
	*x = V1_AccountCreated_Attributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1_AccountCreated_Attributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1_AccountCreated_Attributes) ProtoMessage() {}

func (x *V1_AccountCreated_Attributes) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1_AccountCreated_Attributes.ProtoReflect.Descriptor instead.
func (*V1_AccountCreated_Attributes) Descriptor() ([]byte, []int) {
	return file_events_v1_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *V1_AccountCreated_Attributes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *V1_AccountCreated_Attributes) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

var File_events_v1_proto protoreflect.FileDescriptor

var file_events_v1_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x9b, 0x02, 0x0a, 0x02, 0x56, 0x31, 0x1a, 0x4b, 0x0a, 0x06, 0x54, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x4f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x1a, 0xc7, 0x01, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6f, 0x63, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x64, 0x4f, 0x6e, 0x12, 0x4a, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0x2e, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x2f, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x73, 0x65,
	0x6c, 0x75, 0x69, 0x73, 0x38, 0x39, 0x30, 0x36, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x2d, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_events_v1_proto_rawDescOnce sync.Once
	file_events_v1_proto_rawDescData = file_events_v1_proto_rawDesc
)

func file_events_v1_proto_rawDescGZIP() []byte {
	file_events_v1_proto_rawDescOnce.Do(func() {
		file_events_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_v1_proto_rawDescData)
	})
	return file_events_v1_proto_rawDescData
}

var file_events_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_events_v1_proto_goTypes = []interface{}{
	(*V1)(nil),                           // 0: integrations.V1
	(*V1_Tested)(nil),                    // 1: integrations.V1.Tested
	(*V1_AccountCreated)(nil),            // 2: integrations.V1.AccountCreated
	(*V1_AccountCreated_Attributes)(nil), // 3: integrations.V1.AccountCreated.Attributes
}
var file_events_v1_proto_depIdxs = []int32{
	3, // 0: integrations.V1.AccountCreated.attributes:type_name -> integrations.V1.AccountCreated.Attributes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_v1_proto_init() }
func file_events_v1_proto_init() {
	if File_events_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_events_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1_Tested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1_AccountCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1_AccountCreated_Attributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_proto_goTypes,
		DependencyIndexes: file_events_v1_proto_depIdxs,
		MessageInfos:      file_events_v1_proto_msgTypes,
	}.Build()
	File_events_v1_proto = out.File
	file_events_v1_proto_rawDesc = nil
	file_events_v1_proto_goTypes = nil
	file_events_v1_proto_depIdxs = nil
}
